---
title: "Starter Notebook"
author: "Adaobi Nwankwo, Scientist"
format: html
execute:
  keep-md: true
---

```{r setup, include = FALSE}
#Load in any packages you need
rm(list = ls())
library(tidyverse)

#Read in any data

```

```{r}
nucleotides <- c("Adenine (A)", "Cytosine (C), ", "Guanine (G)", "Thymine (T)")

nucleotides
```

```{r}
genomeLength <- 15

randGenome <- sample(nucleotides, size = genomeLength, replace = TRUE)

paste(randGenome, collapse = "")
```

```{r}
genomeLength <- 1500

randGenome <- sample(nucleotides, size = genomeLength, replace = TRUE)

paste(randGenome, collapse = "")
```

```{r}
set.seed(215)
genomeLength <- 100

randGenome <- sample(nucleotides, size = genomeLength, replace = TRUE)

paste(randGenome, collapse = "")

```

```{r}
mySum <- 0

for(i in 1:10){
  mySum <- mySum + i
  print(mySum)
}
```

```{r}
myProduct <- 1

for(j in 1:15){
  myProduct <- myProduct + i
  print(myProduct)
}
```

```{r}
nucleotides <- c("A", "C", "G", "T")
genomeLength <- 10

randGenome <- paste(
  sample(nucleotides, size = genomeLength, replace = TRUE),
                   collapse = "")
print(randGenome)
```

```{r}
randGenome <- sample(nucleotides, size=genomeLength, replace = TRUE)
randGenome
randGenome <- paste(randGenome, collapse = "")
randGenome

for(j in 1:15){
  print(str_sub(randGenome, start = 1, end = 1))
}
```

```{r}
for(i in 1:nchar(randGenome)){
  if(str_sub(randGenome, start = i, end = i) == "A"){
    print(str_sub(randGenome, start = i, end = i))
  }
}
```

```{r}
for(i in 1:nchar(randGenome)){
  if(str_sub(randGenome, start = i, end = i) == "G"){
    print(str_sub(randGenome, start = i, end = i))
  }
}
```

```{r}
for(i in 1:nchar(randGenome)){
  if(str_sub(randGenome, start = i, end = i) == "T"){
    print(str_sub(randGenome, start = i, end = i))
  }
}
```

```{r}
for(i in 1:nchar(randGenome)){
  if(str_sub(randGenome, start = i, end = i) == "C"){
    print(str_sub(randGenome, start = i, end = i))
  }
}
```
